<!DOCTYPE html><html><head><link rel="stylesheet" type="text/css" href="elisp.css"><title>11.7.2 示例 catch和 throw</title></head><body lang="en" bgcolor="#FFFFFF" text="#000000" link="#0000FF" vlink="#800080" alink="#FF0000"><h3 class="subsection">11.7.2 示例 catch和 throw</h3>
<div class="nav-panel"><p>Next: <a href="11.7.3_错误.html">错误</a>, Previous: <a href="11.7.1_显式非本地出口：_catch和_throw.html">显式非本地出口：_catch和_throw</a>, Up: <a href="11.7_非本地出口.html">非本地出口.</a> &nbsp; [<a href="00_content.htm" title="Table of contents" rel="contents">Contents</a>]</p></div></body></html><hr/><p>使用 catch 和 throw 的一种方法是退出双重嵌套循环。（在大多数语言中，这将通过 goto 完成。）这里我们计算 i 和 j 从 0 到 9 变化的 (foo ij)：
</p><div class="lisp">
<pre class="lisp">(defun search-foo ()
  (catch 'loop
    (let ((i 0))
      (while (&lt; i 10)
        (let ((j 0))
          (while (&lt; j 10)
            (if (foo i j)
                (throw 'loop (list i j)))
            (setq j (1+ j))))
        (setq i (1+ i))))))
</pre></div>
<p>如果 foo 返回非 nil，我们立即停止并返回 i 和 j 的列表。如果 foo 总是返回 nil，则 catch 正常返回，并且值为 nil，因为这是 while 的结果。
</p>
<p>这里有两个棘手的例子，略有不同，同时显示两个返回点。首先，两个相同标签的返回点，hack：
</p><div class="lisp">
<pre class="lisp">(defun catch2 (tag)
  (catch tag
    (throw 'hack 'yes)))
⇒ catch2


(catch 'hack
  (print (catch2 'hack))
  'no)
-| yes
⇒ no
</pre></div>
<p>由于两个返回点都有与投掷相匹配的标签，因此它转到内部的那个，即在 catch2 中建立的那个。因此，catch2 正常返回值为 yes，并打印该值。最后，外部捕获中的第二个主体形式，即 <code>否</code> ，被评估并从外部捕获返回。
</p>
<p>现在让我们更改给 catch2 的参数：
</p><div class="lisp">
<pre class="lisp">(catch 'hack
  (print (catch2 'quux))
  'no)
⇒ yes
</pre></div>
<p>我们仍然有两个返回点，但这次只有外面的一个有标签 hack；  内部的有标签 quux 。因此， throw 使外部 catch 返回值 yes。函数 print 永远不会被调用，并且 body-form ’no 永远不会被评估。
</p>
<hr/>

<div class="nav-panel"><p>Next: <a href="11.7.3_错误.html">错误</a>, Previous: <a href="11.7.1_显式非本地出口：_catch和_throw.html">显式非本地出口：_catch和_throw</a>, Up: <a href="11.7_非本地出口.html">非本地出口.</a> &nbsp; [<a href="00_content.htm" title="Table of contents" rel="contents">Contents</a>]</p></div></body></html>